name: Deploy to VPS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Uygulama dizinine git
          cd /var/www/yksquiz.fun
          
          # Eski dosyaları yedekle
          sudo cp -r public public_backup_$(date +%Y%m%d_%H%M%S)
          
          # Yeni dosyaları kopyala
          sudo rm -rf public/*
          
          # Build dosyalarını kopyala (bu adımı daha sonra düzenleyeceğiz)
          echo "Build dosyaları hazırlanıyor..."
          
          # Nginx'i yeniden başlat
          sudo systemctl reload nginx
          
          echo "Deployment tamamlandı!"
          
    - name: Copy build files to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        source: "build/*"
        target: "/tmp/yksquiz-build"
        strip_components: 1
        
    - name: Deploy files to web directory
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Uygulama dizinine git
          cd /var/www/yksquiz.fun
          
          # Eski dosyaları yedekle
          sudo cp -r public public_backup_$(date +%Y%m%d_%H%M%S) 2>/dev/null || true
          
          # Yeni dosyaları kopyala
          sudo rm -rf public/*
          sudo cp -r /tmp/yksquiz-build/* public/
          
          # Geçici dosyaları temizle
          sudo rm -rf /tmp/yksquiz-build
          
          # Dosya izinlerini ayarla
          sudo chown -R www-data:www-data public/
          sudo chmod -R 755 public/
          
          # Nginx'i yeniden başlat
          sudo systemctl reload nginx
          
          echo "Deployment tamamlandı!" 